import json

from pymilvus import MilvusClient, DataType, Function, FunctionType

collection_name = "my_collection"
client = MilvusClient("./milvus_demo.db")


def create_collection():
    if client.has_collection(collection_name):
        client.drop_collection(collection_name)

    schema = client.create_schema()

    analyzer_params = {"tokenizer": "jieba", "filter": ["cnalphanumonly"]}
    schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True, auto_id=True, description="id")
    schema.add_field(field_name="text", datatype=DataType.VARCHAR, max_length=1000, enable_analyzer=True, analyzer_params=analyzer_params, description="raw text of chunk")
    schema.add_field(field_name="text_dense", datatype=DataType.FLOAT_VECTOR, dim=1024, description="text dense embedding")
    schema.add_field(field_name="text_sparse", datatype=DataType.SPARSE_FLOAT_VECTOR, description="text sparse embedding auto-generated by the built-in BM25 function")
    schema.add_field(field_name="category", datatype=DataType.VARCHAR, max_length=16, description="doc category")

    bm25_function = Function(
        name="text_bm25_emb",
        input_field_names=["text"],
        output_field_names=["text_sparse"],
        function_type=FunctionType.BM25,
    )
    schema.add_function(bm25_function)

    index_params = client.prepare_index_params()

    index_params.add_index(
        field_name="text_dense",
        index_name="text_dense_index",
        index_type="AUTOINDEX",  # local mode only support FLAT IVF_FLAT AUTOINDEX
        metric_type="COSINE",
    )

    index_params.add_index(
        field_name="text_sparse",
        index_name="text_sparse_index",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    # 报错 create_index only supports vector fields
    # index_params.add_index(
    #     field_name="category",
    #     index_type="BITMAP",
    #     index_name="category_index",
    #     metric_type="NONE",
    # )

    client.create_collection(collection_name=collection_name, schema=schema, index_params=index_params)


if __name__ == "__main__":
    json_file = "dataset/doc3.json"

    with open(json_file, "r", encoding="utf-8") as f:
        json_content = json.load(f)
        chunks = json_content["chunks"]

    res = client.insert(
        collection_name=collection_name, data=[{"text": chunk["rewritten_content"], "text_dense": chunk["embedding"], "category": json_content["category"]} for chunk in chunks]
    )
    print("Generated IDs:", res.get("ids"))
